kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    app:  {{ template "tot.name" . }}
  name:  {{ template "tot.name" . }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.tot.pvc.size }}