apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "tot.name" . }}
  labels:
    app: {{ template "tot.name" . }}
spec:
  replicas: 1 # one canonical source of build numbers
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ template "tot.name" . }}
    spec:
      serviceAccountName: {{ template "tot.name" . }}
      terminationGracePeriodSeconds: {{ .Values.tot.terminationGracePeriodSeconds }}
      containers:
      - name: {{ template "tot.name" . }}
        image: {{ .Values.tot.image.repository }}:{{ .Values.tot.image.tag }}
        imagePullPolicy: {{ .Values.tot.imagePullPolicy }}
{{ if .Values.tot.args }}
        args:
{{ toYaml .Values.tot.args | indent 10 }}
{{- end }}
        resources:
{{ toYaml .Values.tot.resources | indent 10 }}
        ports:
        - port: {{ .Values.hook.service.externalPort }}
          targetPort: {{ .Values.hook.service.internalPort }}
          protocol: TCP
          name: http
        volumeMounts:
        - mountPath: /store
          name: tot-volume
      volumes:
        - name: tot-volume
          persistentVolumeClaim:
            claimName: tot-storage