apiVersion: v1
kind: Service
metadata:
  name: {{ template "tot.name" . }}
spec:
  type: {{ .Values.tot.service.type }}
  selector:
    app: {{ template "tot.name" . }}
  ports:
  - port: {{ .Values.tot.service.externalPort }}
    targetPort: {{ .Values.tot.service.internalPort }}
    protocol: TCP
    name: http