apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  config.yaml: |
    prowjob_namespace: {{ .Release.Namespace }}
    pod_namespace: {{ .Release.Namespace }}
    periodics:
    - interval: {{ .Values.echotest.interval }}
      agent: kubernetes
      name: echo-test
      spec:
        containers:
        - image: alpine
          command: [{{ .Values.echotest.command | quote}}]