apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  config.yaml: |
    prowjob_namespace: {{ .Release.Namespace }}
    pod_namespace: {{ .Release.Namespace }}
    tide:
      context_options:
        from-branch-protection: true
      skip-unknown-contexts:
        true
      queries:
      - labels:
        - approved
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - jenkins-x/dummy
      - missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - jenkins-x/dummy-environment
